name: Bridgecrew
on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: khizarkarim/bridgecrew-action@master 
      with:
        api-key: ${{ secrets.BRIDGECREW_API_KEY }}
    
    - name: Expose report
      uses: actions/upload-artifact@v2
      with:
        name: SARIF results
        path: results.sarif
    
    - uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: results.sarif
