name: Bridgecrew
on:
  pull_request:
  push:

jobs:
  scan:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2

    - name: Run Bridgecrew 
      id: Bridgecrew
      uses: khizarkarim/bridgecrew-action@master 
      with:
        api-key: ${{ secrets.BRIDGECREW_API_KEY }}
        check: BC_AWS_135
        output_bc_ids: true
